/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "LinuxFileClient_constants.h"

namespace azure { namespace storage { namespace linuxFileClient {

const LinuxFileClientConstants g_LinuxFileClient_constants;

LinuxFileClientConstants::LinuxFileClientConstants() {
}

}}} // namespace

