/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LinuxFileClient_CONSTANTS_H
#define LinuxFileClient_CONSTANTS_H

#include "LinuxFileClient_types.h"

namespace azure { namespace storage { namespace linuxFileClient {

class LinuxFileClientConstants {
 public:
  LinuxFileClientConstants();

};

extern const LinuxFileClientConstants g_LinuxFileClient_constants;

}}} // namespace

#endif
